<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DEA Write Up</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="DEA_files/libs/clipboard/clipboard.min.js"></script>
<script src="DEA_files/libs/quarto-html/quarto.js"></script>
<script src="DEA_files/libs/quarto-html/popper.min.js"></script>
<script src="DEA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DEA_files/libs/quarto-html/anchor.min.js"></script>
<link href="DEA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DEA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DEA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DEA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DEA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DEA Write Up</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Loading Relevant Libraries</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Adding Google Trends Data</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2825 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 173949 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 168242 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 139749 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 175729 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 152884 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 106965 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 115042 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 67236 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 306790 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 513 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 183816 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): schname, keyword, monthorweek
dbl (3): schid, keynum, index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'schname'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   schname [2]
  schname                monthly_date mean_std_index
  &lt;chr&gt;                  &lt;date&gt;                &lt;dbl&gt;
1 40%                    NA                 NaN     
2 aaniiih nakoda college 2013-03-01           2.12  
3 aaniiih nakoda college 2013-04-01          -0.728 
4 aaniiih nakoda college 2013-05-01          -0.694 
5 aaniiih nakoda college 2013-06-01           0.0186
6 aaniiih nakoda college 2013-07-01           0.145 </code></pre>
</div>
</div>
<p>Reading in scorecard data</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 7804 Columns: 122
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (115): INSTNM, CITY, STABBR, INSTURL, NPCURL, LOCALE, HBCU, PBI, ANNHI, ...
dbl   (7): UNITID, OPEID, opeid6, HCM2, PREDDEG, CONTROL, CURROPER

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Importing Id_name_data and cleaning for merger</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 125
# Groups:   schname [1]
  schname   monthly_date mean_std_index unitid  opeid opeid6 INSTNM CITY  STABBR
  &lt;chr&gt;     &lt;date&gt;                &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; 
1 abilene … 2015-09-01           0.356  222178 353700   3537 Abile… Abil… TX    
2 abilene … 2015-10-01           0.0598 222178 353700   3537 Abile… Abil… TX    
3 abilene … 2015-11-01          -0.404  222178 353700   3537 Abile… Abil… TX    
4 abilene … 2015-12-01          -1.26   222178 353700   3537 Abile… Abil… TX    
5 abilene … 2016-01-01          -0.148  222178 353700   3537 Abile… Abil… TX    
6 abilene … 2016-02-01          -0.458  222178 353700   3537 Abile… Abil… TX    
# ℹ 116 more variables: INSTURL &lt;chr&gt;, NPCURL &lt;chr&gt;, HCM2 &lt;dbl&gt;, PREDDEG &lt;dbl&gt;,
#   CONTROL &lt;dbl&gt;, LOCALE &lt;chr&gt;, HBCU &lt;chr&gt;, PBI &lt;chr&gt;, ANNHI &lt;chr&gt;,
#   TRIBAL &lt;chr&gt;, AANAPII &lt;chr&gt;, HSI &lt;chr&gt;, NANTI &lt;chr&gt;, MENONLY &lt;chr&gt;,
#   WOMENONLY &lt;chr&gt;, RELAFFIL &lt;chr&gt;, SATVR25 &lt;chr&gt;, SATVR75 &lt;chr&gt;,
#   SATMT25 &lt;chr&gt;, SATMT75 &lt;chr&gt;, SATWR25 &lt;chr&gt;, SATWR75 &lt;chr&gt;, SATVRMID &lt;chr&gt;,
#   SATMTMID &lt;chr&gt;, SATWRMID &lt;chr&gt;, ACTCM25 &lt;chr&gt;, ACTCM75 &lt;chr&gt;,
#   ACTEN25 &lt;chr&gt;, ACTEN75 &lt;chr&gt;, ACTMT25 &lt;chr&gt;, ACTMT75 &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>Regression Portion</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in log(mean_std_index): NaNs produced</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: 8,837 observations removed because of NA values (LHS: 8,837).</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                          reg_model
Dependent Var.: log(mean_std_index)
                                   
Constant           41.48*** (4.518)
HighEarning         0.2692 (0.4241)
LowEarning          0.2567 (0.4242)
monthly_date    -0.0026*** (0.0003)
_______________ ___________________
S.E. type                       IID
Observations                  4,904
R2                          0.01873
Adj. R2                     0.01813
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: log(mean_std_index)
Observations: 4,904 
Standard-errors: IID 
              Estimate Std. Error   t value  Pr(&gt;|t|)    
(Intercept)  41.480347   4.517543  9.182058 &lt; 2.2e-16 ***
HighEarning   0.269206   0.424084  0.634794   0.52559    
LowEarning    0.256668   0.424154  0.605129   0.54512    
monthly_date -0.002579   0.000268 -9.628585 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 1.19668   Adj. R2: 0.018129</code></pre>
</div>
</div>
<p>Graph</p>
<p>This graph shows the distribution of observations based on median earnings and mean standard index. this graph is separated by high earnings and low earnings</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DEA_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The question of this project was among colleges that predominantly grant bachelor’s degrees, did the release of the Scorecard shift student interest to high- earnings colleges relative to low- earning ones?</p>
<p>Notes about the data used:</p>
<ul>
<li>my data takes into account that the median income is 42,000 based off of that I determined that any salary below 42,000 is “low earning” while anything above is “high earning”</li>
</ul>
<p>based off the information above when the regression was ran I can answer this question by stating the following:</p>
<p>The introduction of the College Scorecard increased search activity on Google Trends for colleges with high-earning graduates by 0.2692 units relative to what it did for colleges with low-earning graduates, with a standard error of 0.4241. This result comes from the coefficients in my regression. The t-value associated with HighEarning is 0.6348, with a p-value of 0.5256, suggesting that the coefficient is not statistically significant. Similarly, for LowEarning, the t-value is 0.6051 with a p-value of 0.5451, indicating no statistical significance. The coefficient for monthly_date is -0.0026 with a standard error of 0.0003, and it is statistically significant (p-value &lt; 2.2e-16). The RMSE of the model is 1.19668, and the adjusted R-squared is 0.0181.</p>
<p>Holding everything constant a one unit increase in high earning is associated with a 0.2692 increase in the mean standard index. However, since our p-value of 0.5256, this suggests that this coefficient isn’t statistically significant. We cannot determine if there is a relationship between high earning and mean standard index. This also holds true for low earning individuals which has a lower coefficient (.2567) and a higher P-value (0.5451). This leads me to believe that there is no correlation between the introduction of the college scorecard on high earning and low earning individuals.</p>
<p><br>
</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>